# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'

target 'CPMD_Week2' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CPMD_Week2

  target 'CPMD_Week2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CPMD_Week2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
